export const Employers = [
    {
        name: "Ayesha Rahman",
        email: "ayesha@techflare.io",
        password: "securePass123",
        companyName: "TechFlare Solutions",
        companyDescription:
            "A software development agency specializing in AI-driven web applications and automation tools.",
        designation: "HR Manager",
        role: "employer",
        phone: "+8801711223344",
        website: "https://www.techflare.io",
        address: {
            street: "45 Green Road",
            city: "Dhaka",
            state: "Dhaka",
            country: "Bangladesh",
            postalCode: "1205",
        },
        profileImage: "https://randomuser.me/api/portraits/women/45.jpg",
        companyLogo:
            "https://res.cloudinary.com/demo/image/upload/v1691234567/techflare-logo.png",
        industry: "Software Development",
        companySize: "51-200",
        establishedYear: 2017,
        jobsPosted: [],
    },
    {
        name: "Rafiq Hossain",
        email: "rafiq@buildhub.com",
        password: "strongBuild987",
        companyName: "BuildHub Engineering",
        companyDescription:
            "An infrastructure design and construction company delivering sustainable engineering solutions.",
        designation: "Project Director",
        role: "employer",
        phone: "+8801811334455",
        website: "https://www.buildhub.com",
        address: {
            street: "12 Kazi Nazrul Avenue",
            city: "Chittagong",
            state: "Chittagong",
            country: "Bangladesh",
            postalCode: "4000",
        },
        profileImage: "https://randomuser.me/api/portraits/men/29.jpg",
        companyLogo:
            "https://res.cloudinary.com/demo/image/upload/v1691234567/buildhub-logo.png",
        industry: "Construction & Engineering",
        companySize: "201-500",
        establishedYear: 2005,
        jobsPosted: [],
    },
    {
        name: "Farhana Akter",
        email: "farhana@meditech.org",
        password: "meditechPro88",
        companyName: "MediTech Healthcare",
        companyDescription:
            "A healthcare technology company providing telemedicine and diagnostic software solutions.",
        designation: "Recruitment Lead",
        role: "employer",
        phone: "+8801911778899",
        website: "https://www.meditech.org",
        address: {
            street: "90 Lake View Road",
            city: "Sylhet",
            state: "Sylhet",
            country: "Bangladesh",
            postalCode: "3100",
        },
        profileImage: "https://randomuser.me/api/portraits/women/41.jpg",
        companyLogo:
            "https://res.cloudinary.com/demo/image/upload/v1691234567/meditech-logo.png",
        industry: "Healthcare & Biotechnology",
        companySize: "501-1000",
        establishedYear: 2010,
        jobsPosted: [],
    },
    {
        name: "Imran Kabir",
        email: "imran@foodverse.co",
        password: "tasteTheWorld12",
        companyName: "FoodVerse Co.",
        companyDescription:
            "A leading online food delivery platform connecting customers with local restaurants.",
        designation: "Head of Operations",
        role: "employer",
        phone: "+8801711995566",
        website: "https://www.foodverse.co",
        address: {
            street: "78 Gulshan Avenue",
            city: "Dhaka",
            state: "Dhaka",
            country: "Bangladesh",
            postalCode: "1212",
        },
        profileImage: "https://randomuser.me/api/portraits/men/52.jpg",
        companyLogo:
            "https://res.cloudinary.com/demo/image/upload/v1691234567/foodverse-logo.png",
        industry: "Food & Beverage",
        companySize: "1000+",
        establishedYear: 2015,
        jobsPosted: [],
    },
    {
        name: "Nusrat Jahan",
        email: "nusrat@learnhub.edu",
        password: "learnSmart789",
        companyName: "LearnHub Academy",
        companyDescription:
            "An EdTech startup offering interactive online learning experiences for students worldwide.",
        designation: "Talent Acquisition Manager",
        role: "employer",
        phone: "+8801555990088",
        website: "https://www.learnhub.edu",
        address: {
            street: "34 College Road",
            city: "Rajshahi",
            state: "Rajshahi",
            country: "Bangladesh",
            postalCode: "6000",
        },
        profileImage: "https://randomuser.me/api/portraits/women/36.jpg",
        companyLogo:
            "https://res.cloudinary.com/demo/image/upload/v1691234567/learnhub-logo.png",
        industry: "Education Technology",
        companySize: "11-50",
        establishedYear: 2018,
        jobsPosted: [],
    },
];
