export const fakeCandidates = [
  {
    name: "Sadia Rahman",
    email: "sadia.rahman@gmail.com",
    phone: "+8801789234567",
    profileImage: "https://randomuser.me/api/portraits/women/65.jpg",
    address: "Dhanmondi, Dhaka, Bangladesh",
    bio: "Frontend developer passionate about React, TypeScript, and clean UI design.",
    education: [
      {
        institution: "University of Dhaka",
        degree: "BSc in Computer Science",
        fieldOfStudy: "Computer Science and Engineering",
        startDate: "2018-01-01",
        endDate: "2022-01-01",
      },
    ],
    experience: [
      {
        company: "TechNova Solutions",
        position: "Frontend Developer",
        startDate: "2022-03-01",
        isCurrentlyWorking: true,
        responsibilities: "Developing scalable UI components with React and TailwindCSS.",
      },
    ],
    skills: ["React", "TypeScript", "TailwindCSS", "Node.js"],
    resume: "https://drive.google.com/file/d/1SadiaResume/view",
    socialLinks: {
      linkedin: "https://linkedin.com/in/sadiarahman",
      github: "https://github.com/sadiarahman",
      portfolio: "https://sadiarahman.dev",
    },
  },
  {
    name: "Tanvir Ahmed",
    email: "tanvir.ahmed@gmail.com",
    phone: "+8801778234990",
    profileImage: "https://randomuser.me/api/portraits/men/32.jpg",
    address: "Uttara, Dhaka, Bangladesh",
    bio: "Full Stack developer specializing in Node.js and Express APIs.",
    education: [
      {
        institution: "Ahsanullah University of Science & Technology",
        degree: "BSc in Software Engineering",
        startDate: "2017-01-01",
        endDate: "2021-01-01",
      },
    ],
    experience: [
      {
        company: "CodeVerse",
        position: "Backend Engineer",
        startDate: "2021-06-01",
        endDate: "2024-02-01",
        responsibilities: "Built REST APIs and optimized database queries for performance.",
      },
    ],
    skills: ["Node.js", "Express", "MongoDB", "JWT", "Docker"],
    resume: "https://drive.google.com/file/d/1TanvirResume/view",
    socialLinks: {
      linkedin: "https://linkedin.com/in/tanvirahmed",
      github: "https://github.com/tanvirahmed",
    },
  },
  {
    name: "Rafiul Islam",
    email: "rafiul.islam@gmail.com",
    phone: "+8801766322001",
    profileImage: "https://randomuser.me/api/portraits/men/44.jpg",
    address: "Chittagong, Bangladesh",
    bio: "ML Engineer focused on Computer Vision and Deep Learning.",
    education: [
      {
        institution: "University of Chittagong",
        degree: "BSc in EEE",
        startDate: "2016-01-01",
        endDate: "2020-01-01",
      },
    ],
    experience: [
      {
        company: "AI Vision Lab",
        position: "Machine Learning Engineer",
        startDate: "2021-04-01",
        isCurrentlyWorking: true,
        responsibilities: "Developing CNN-based models for medical imaging.",
      },
    ],
    skills: ["Python", "TensorFlow", "Keras", "OpenCV", "PyTorch"],
    resume: "https://drive.google.com/file/d/1RafiulResume/view",
    socialLinks: {
      linkedin: "https://linkedin.com/in/rafiulislm",
      github: "https://github.com/rafiulislm",
    },
  },
  {
    name: "Mehedi Hasan",
    email: "mehedi.hasan@gmail.com",
    phone: "+8801999334411",
    profileImage: "https://randomuser.me/api/portraits/men/52.jpg",
    address: "Mirpur, Dhaka",
    bio: "UI/UX Designer who transforms wireframes into clean user experiences.",
    skills: ["Figma", "Adobe XD", "Framer", "React", "Design Systems"],
    education: [
      {
        institution: "BRAC University",
        degree: "BFA in Design & Technology",
        startDate: "2018-01-01",
        endDate: "2022-01-01",
      },
    ],
    experience: [
      {
        company: "DesignCraft",
        position: "Product Designer",
        startDate: "2022-05-01",
        isCurrentlyWorking: true,
        responsibilities: "Created design systems and prototyped user flows.",
      },
    ],
    resume: "https://drive.google.com/file/d/1MehediResume/view",
  },
  {
    name: "Anika Chowdhury",
    email: "anika.chowdhury@gmail.com",
    phone: "+8801877332211",
    profileImage: "https://randomuser.me/api/portraits/women/43.jpg",
    address: "Sylhet, Bangladesh",
    bio: "Mobile developer specializing in React Native and cross-platform apps.",
    skills: ["React Native", "Expo", "Firebase", "TypeScript", "Redux"],
    education: [
      {
        institution: "Metropolitan University",
        degree: "BSc in Computer Science",
        startDate: "2017-01-01",
        endDate: "2021-01-01",
      },
    ],
    experience: [
      {
        company: "Appify Bangladesh",
        position: "React Native Developer",
        startDate: "2021-09-01",
        isCurrentlyWorking: true,
        responsibilities: "Built mobile apps for e-commerce and fintech clients.",
      },
    ],
    resume: "https://drive.google.com/file/d/1AnikaResume/view",
  },
  {
    name: "Farhan Hossain",
    email: "farhan.hossain@gmail.com",
    phone: "+8801555448877",
    profileImage: "https://randomuser.me/api/portraits/men/23.jpg",
    address: "Banani, Dhaka",
    bio: "Data analyst with strong experience in SQL, Power BI, and Python.",
    skills: ["SQL", "Power BI", "Pandas", "Matplotlib", "Excel"],
    education: [
      {
        institution: "North South University",
        degree: "BBA in Management Information Systems",
        startDate: "2016-01-01",
        endDate: "2020-01-01",
      },
    ],
    experience: [
      {
        company: "DataEdge",
        position: "Data Analyst",
        startDate: "2020-03-01",
        isCurrentlyWorking: true,
        responsibilities: "Analyzing business performance and visualizing insights.",
      },
    ],
    resume: "https://drive.google.com/file/d/1FarhanResume/view",
  },
  {
    name: "Jannatul Ferdous",
    email: "jannatul.ferdous@gmail.com",
    phone: "+8801799992233",
    profileImage: "https://randomuser.me/api/portraits/women/60.jpg",
    address: "Khulna, Bangladesh",
    bio: "Backend developer building scalable REST APIs using Express and PostgreSQL.",
    skills: ["Node.js", "Express", "PostgreSQL", "Redis", "Prisma"],
    experience: [
      {
        company: "TechHive",
        position: "Backend Developer",
        startDate: "2021-07-01",
        isCurrentlyWorking: true,
      },
    ],
    resume: "https://drive.google.com/file/d/1JannatResume/view",
  },
  {
    name: "Nayeem Rahman",
    email: "nayeem.rahman@gmail.com",
    phone: "+8801877123444",
    profileImage: "https://randomuser.me/api/portraits/men/41.jpg",
    address: "Rajshahi, Bangladesh",
    bio: "Junior software engineer learning MERN stack development.",
    skills: ["JavaScript", "React", "MongoDB", "Express"],
    education: [
      {
        institution: "Rajshahi University",
        degree: "BSc in CSE",
        startDate: "2019-01-01",
        endDate: "2023-01-01",
      },
    ],
    resume: "https://drive.google.com/file/d/1NayeemResume/view",
  },
  {
    name: "Samira Noor",
    email: "samira.noor@gmail.com",
    phone: "+8801999332200",
    profileImage: "https://randomuser.me/api/portraits/women/30.jpg",
    address: "Barishal, Bangladesh",
    bio: "Content strategist and technical writer for tech startups.",
    skills: ["Copywriting", "SEO", "Technical Documentation", "Content Strategy"],
    resume: "https://drive.google.com/file/d/1SamiraResume/view",
  },
  {
    name: "Abrar Hossain",
    email: "abrar.hossain@gmail.com",
    phone: "+8801777889911",
    profileImage: "https://randomuser.me/api/portraits/men/60.jpg",
    address: "Comilla, Bangladesh",
    bio: "DevOps engineer focused on CI/CD pipelines and automation.",
    skills: ["AWS", "Docker", "Kubernetes", "Linux", "CI/CD"],
    experience: [
      {
        company: "CloudSphere",
        position: "DevOps Engineer",
        startDate: "2020-05-01",
        isCurrentlyWorking: true,
      },
    ],
    resume: "https://drive.google.com/file/d/1AbrarResume/view",
  },
];
